/**
 * Baza de date oficială H-TIME - Versiune Multilingvă Completă (6 Limbi)
 * Conține 35 de produse cu Nume și Descrieri traduse integral.
 * Prețurile sunt în EURO (€) și se convertesc automat în interfață.
 */

const produse = [
  {
    id: 1,
    categorie: "ceasuri",
    nume: "Ceas Rolex Oyster Luxury",
    nume_en: "Rolex Oyster Luxury Watch",
    nume_fr: "Montre Rolex Oyster de Luxe",
    nume_de: "Rolex Oyster Luxusuhr",
    nume_es: "Reloj Rolex Oyster Luxury",
    nume_it: "Orologio Rolex Oyster Luxury",
    descriere: "O piesă atemporală ce îmbină precizia elvețiană cu eleganța aurului de 18k. Un simbol al succesului.",
    descriere_en: "A timeless piece combining Swiss precision with 18k gold elegance. A symbol of success.",
    descriere_fr: "Une pièce intemporelle alliant la précision suisse à l'élégance de l'or 18 carats. Un symbole de succès.",
    descriere_de: "Ein zeitloses Stück, das Schweizer Präzision cu 18 Karat Gold-Eleganz kombiniert. Ein Symbol des Erfolgs.",
    descriere_es: "Una pieza atemporal que combina la precisión suiza con la elegancia del oro de 18k. Un símbolo de éxito.",
    descriere_it: "Un pezzo senza tempo che unisce la precisione svizzera all'eleganza dell'oro 18 carati. Un simbolo di successo.",
    pret: 950,
    pretVechi: 1200,
    isSale: true,
    imagine: "ceas1.jpg",
    galerie: ["ceas2.jpg", "ceas.jpg"]
  },
  {
    id: 2,
    categorie: "inele",
    nume: "Inel Aur Hera",
    nume_en: "Hera Gold Ring",
    nume_fr: "Bague en Or Hera",
    nume_de: "Hera Goldring",
    nume_es: "Anillo de Oro Hera",
    nume_it: "Anello in Oro Hera",
    descriere: "Inspirat de zeița Hera, acest inel din aur masiv simbolizează devotamentul și puterea feminină.",
    descriere_en: "Inspired by the goddess Hera, this solid gold ring symbolizes devotion and feminine power.",
    descriere_fr: "Inspirée par la déesse Héra, cette bague en or massif symbolise la dévotion et le pouvoir féminin.",
    descriere_de: "Inspiriert von der Göttin Hera, symbolisiert dieser massive Goldring Hingabe und weibliche Kraft.",
    descriere_es: "Inspirado en la diosa Hera, este anillo de oro macizo simboliza la devoción y el poder femenino.",
    descriere_it: "Ispirato alla dea Era, questo anello in oro massiccio simboleggia la devozione e il potere femminile.",
    pret: 150,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: ["inel2.jpg", "ring.jpg"]
  },
  {
    id: 3,
    categorie: "cercei",
    nume: "Cercei Diamond Drop",
    nume_en: "Diamond Drop Earrings",
    nume_fr: "Boucles d'oreilles Diamond Drop",
    nume_de: "Diamond Drop Ohrringe",
    nume_es: "Pendientes Diamond Drop",
    nume_it: "Orecchini Diamond Drop",
    descriere: "Cercei eleganți cu diamante selecționate, creați pentru a capta lumina la fiecare mișcare.",
    descriere_en: "Elegant earrings with selected diamonds, designed to catch the light with every move.",
    descriere_fr: "Boucles d'oreilles élégantes avec diamants sélectionnés, conçues pour capter la lumière.",
    descriere_de: "Elegante Ohrringe mit ausgewählten Diamanten, die bei jeder Bewegung das Licht einfangen.",
    descriere_es: "Elegantes pendientes con diamantes seleccionados, diseñados para captar la luz.",
    descriere_it: "Eleganti orecchini con diamanti selezionati, progettati per catturare la luce.",
    pret: 320,
    pretVechi: 450,
    isSale: true,
    imagine: "cercel1.jpg",
    galerie: ["earring.jpg"]
  },
  {
    id: 4,
    categorie: "ceasuri",
    nume: "Ceas Chronos Silver",
    nume_en: "Chronos Silver Watch",
    nume_fr: "Montre Chronos Silver",
    nume_de: "Chronos Silver Uhr",
    nume_es: "Reloj Chronos Silver",
    nume_it: "Orologio Chronos Silver",
    descriere: "Un design minimalist din oțel inoxidabil. Chronos Silver este partenerul stilului business.",
    descriere_en: "A minimalist design in stainless steel. Chronos Silver is the partner for business style.",
    descriere_fr: "Un design minimaliste en acier inoxydable. Chronos Silver est le partenaire du style business.",
    descriere_de: "Ein minimalistisches Design aus Edelstahl. Chronos Silver ist der Partner für den Business-Stil.",
    descriere_es: "Un diseño minimalista en acero inoxidable. Chronos Silver es el compañero del estilo business.",
    descriere_it: "Un design minimalista in acciaio inossidabile. Chronos Silver è il partner dello stile business.",
    pret: 420,
    isSale: false,
    imagine: "ceas2.jpg",
    galerie: ["ceas.jpg"]
  },
  {
    id: 5,
    categorie: "inele",
    nume: "Inel Safir Royal",
    nume_en: "Royal Sapphire Ring",
    nume_fr: "Bague Saphir Royal",
    nume_de: "Königlicher Saphirring",
    nume_es: "Anillo de Zafiro Real",
    nume_it: "Anello Zaffiro Reale",
    descriere: "Un safir profund înconjurat de diamante mici, montat pe o bandă delicată de aur alb.",
    descriere_en: "A deep sapphire surrounded by small diamonds, set on a delicate white gold band.",
    descriere_fr: "Un saphir profond entouré de petits diamants, monté sur un anneau en or blanc délicat.",
    descriere_de: "Ein tiefer Saphir, umgeben von kleinen Diamanten, gefasst auf einem zarten Weißgoldband.",
    descriere_es: "Un zafiro profundo rodeado de pequeños diamantes, engastado en una delicada banda de oro blanco.",
    descriere_it: "Un profondo zaffiro circondato da piccoli diamanti, incastonato su una delicata fascia in oro bianco.",
    pret: 580,
    pretVechi: 720,
    isSale: true,
    imagine: "inel2.jpg",
    galerie: ["ring.jpg"]
  },
  {
    id: 6,
    categorie: "bratari",
    nume: "Brățară Gold Link",
    nume_en: "Gold Link Bracelet",
    nume_fr: "Bracelet Gold Link",
    nume_de: "Gold Link Armband",
    nume_es: "Pulsera Gold Link",
    nume_it: "Bracciale Gold Link",
    descriere: "Zale lucrate manual ce reflectă măiestria H-TIME. Adaugă un accent de lux oricărei ținute.",
    descriere_en: "Handcrafted links reflecting H-TIME craftsmanship. Adds a luxury accent to any outfit.",
    descriere_fr: "Maillons fabriqués à la main reflétant le savoir-faire H-TIME. Ajoute une touche de luxe.",
    descriere_de: "Handgefertigte Glieder, die die Handwerkskunst von H-TIME widerspiegeln. Ein luxuriöser Akzent.",
    descriere_es: "Eslabones hechos a mano que reflejan la artesanía de H-TIME. Añade un toque de lujo.",
    descriere_it: "Maglie artigianali che riflettono la maestria di H-TIME. Aggiunge un accento di lusso.",
    pret: 210,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 7,
    categorie: "cercei",
    nume: "Cercei Perla Afroditei",
    nume_en: "Aphrodite's Pearl Earrings",
    nume_fr: "Boucles d'oreilles Perle d'Aphrodite",
    nume_de: "Perlenohrringe der Aphrodite",
    nume_es: "Pendientes Perla de Afrodita",
    nume_it: "Orecchini Perla di Afrodite",
    descriere: "Perle naturale de apă sărată cu o strălucire sidefată, inspirate de frumusețea zeiței iubirii.",
    descriere_en: "Natural saltwater pearls with a pearly glow, inspired by the beauty of the goddess of love.",
    descriere_fr: "Perles naturelles d'eau salée au reflet nacré, inspirées par la beauté de la déesse de l'amour.",
    descriere_de: "Natürliche Salzwasserperlen mit perlmuttartigem Glanz, inspiriert von der Göttin der Liebe.",
    descriere_es: "Perlas naturales de agua salada con un brillo nacarado, inspiradas en la diosa del amor.",
    descriere_it: "Perle naturali d'acqua salata con una lucentezza perlacea, ispirate alla dea dell'amore.",
    pret: 180,
    isSale: false,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 8,
    categorie: "ceasuri",
    nume: "Ceas Onyx Night",
    nume_en: "Onyx Night Watch",
    nume_fr: "Montre Onyx Night",
    nume_de: "Onyx Night Uhr",
    nume_es: "Reloj Onyx Night",
    nume_it: "Orologio Onyx Night",
    descriere: "Eleganță în negru absolut. Un ceas rar cu cadran din onix și curea din piele de crocodil.",
    descriere_en: "Elegance in absolute black. A rare watch with an onyx dial and crocodile leather strap.",
    descriere_fr: "L'élégance au noir absolu. Une montre rare avec un cadran en onyx et un bracelet en crocodile.",
    descriere_de: "Eleganz in absolutem Schwarz. Eine seltene Uhr mit Onyx-Zifferblatt und Krokodillederarmband.",
    descriere_es: "Elegancia en negro absoluto. Un reloj poco común con esfera de ónix y correa de cocodrilo.",
    descriere_it: "Eleganza in nero assoluto. Un orologio raro con quadrante in onice e cinturino in coccodrillo.",
    pret: 850,
    pretVechi: 1100,
    isSale: true,
    imagine: "ceas.jpg",
    galerie: []
  },
  {
    id: 9,
    categorie: "ceasuri",
    nume: "Ceas Olympus Gold",
    nume_en: "Olympus Gold Watch",
    nume_fr: "Montre Olympus Gold",
    nume_de: "Olympus Gold Uhr",
    nume_es: "Reloj Olympus Gold",
    nume_it: "Orologio Olympus Gold",
    descriere: "Puterea zeilor la încheietura mâinii tale. Placat integral cu aur de 24k.",
    descriere_en: "The power of the gods on your wrist. Fully plated with 24k gold.",
    descriere_fr: "Le pouvoir des dieux à votre poignet. Entièrement plaqué or 24 carats.",
    descriere_de: "Die Macht der Götter an Ihrem Handgelenk. Vollständig mit 24 Karat Gold vergoldet.",
    descriere_es: "El poder de los dioses en tu muñeca. Totalmente bañado en oro de 24k.",
    descriere_it: "Il potere degli dei al tuo polso. Interamente placcato in oro 24 carati.",
    pret: 1250,
    pretVechi: 1500,
    isSale: true,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 10,
    categorie: "ceasuri",
    nume: "Ceas Poseidon Deep Blue",
    nume_en: "Poseidon Deep Blue Watch",
    nume_fr: "Montre Poseidon Deep Blue",
    nume_de: "Poseidon Deep Blue Uhr",
    nume_es: "Reloj Poseidon Deep Blue",
    nume_it: "Orologio Poseidon Deep Blue",
    descriere: "Rezistență extremă și un cadran de un albastru oceanic hipnotizant.",
    descriere_en: "Extreme durability and a mesmerizing oceanic blue dial.",
    descriere_fr: "Durabilité extrême et cadran bleu océanique fascinant.",
    descriere_de: "Extreme Haltbarkeit und ein faszinierendes ozeanblaues Zifferblatt.",
    descriere_es: "Durabilidad extrema y una esfera azul oceánica fascinante.",
    descriere_it: "Durata estrema e un quadrante blu oceanico ipnotizzante.",
    pret: 680,
    isSale: false,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 11,
    categorie: "inele",
    nume: "Inel Artemis Moon",
    nume_en: "Artemis Moon Ring",
    nume_fr: "Bague Artemis Moon",
    nume_de: "Artemis Moon Ring",
    nume_es: "Anillo Artemis Moon",
    nume_it: "Anello Artemis Moon",
    descriere: "Argint pur cu o piatră a lunii ce reflectă lumina nocturnă.",
    descriere_en: "Pure silver with a moonstone that reflects the night light.",
    descriere_fr: "Argent pur avec une pierre de lune care reflète la lumière nocturne.",
    descriere_de: "Reines Silber mit einem Mondstein, der das Nachtlicht reflektiert.",
    descriere_es: "Plata pura con una piedra lunar que refleja la luz nocturna.",
    descriere_it: "Argento puro con una pietra di luna che riflette la luce notturna.",
    pret: 120,
    pretVechi: 180,
    isSale: true,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 12,
    categorie: "cercei",
    nume: "Cercei Athena Wisdom",
    nume_en: "Athena Wisdom Earrings",
    nume_fr: "Boucles d'oreilles Athena Wisdom",
    nume_de: "Athena Wisdom Ohrringe",
    nume_es: "Pendientes Athena Wisdom",
    nume_it: "Orecchini Athena Wisdom",
    descriere: "Simbolul bufniței sculptat în aur alb, decorat cu safire.",
    descriere_en: "The owl symbol carved in white gold, decorated with sapphires.",
    descriere_fr: "Le symbole de la chouette sculpté en or blanc, décoré de saphirs.",
    descriere_de: "Das in Weißgold geschnitzte Eulensymbol, verziert mit Saphiren.",
    descriere_es: "El símbolo del búho tallado en oro blanco, decorado con zafiros.",
    descriere_it: "Il simbolo del gufo intagliato in oro bianco, decorato con zaffiri.",
    pret: 290,
    isSale: false,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 13,
    categorie: "bratari",
    nume: "Brățară Hermes Speed",
    nume_en: "Hermes Speed Bracelet",
    nume_fr: "Bracelet Hermes Speed",
    nume_de: "Hermes Speed Armband",
    nume_es: "Pulsera Hermes Speed",
    nume_it: "Bracciale Hermes Speed",
    descriere: "O brățară din piele fină cu accente din titan argintiu.",
    descriere_en: "A fine leather bracelet with silver titanium accents.",
    descriere_fr: "Un bracelet en cuir fin avec des accents en titane argenté.",
    descriere_de: "Ein feines Lederarmband mit silbernen Titan-Akzenten.",
    descriere_es: "Una pulsera de cuero fino con detalles de titanio plateado.",
    descriere_it: "Un cinturino in pelle fine con accenti in titanio argento.",
    pret: 95,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 14,
    categorie: "ceasuri",
    nume: "Ceas Apollo Sun",
    nume_en: "Apollo Sun Watch",
    nume_fr: "Montre Apollo Sun",
    nume_de: "Apollo Sun Uhr",
    nume_es: "Reloj Apollo Sun",
    nume_it: "Orologio Apollo Sun",
    descriere: "Mecanism solar într-o carcasă elegantă de aur roz.",
    descriere_en: "Solar mechanism in an elegant rose gold case.",
    descriere_fr: "Mécanisme solaire dans un élégant boîtier en or rose.",
    descriere_de: "Solarwerk in einem eleganten Roségoldgehäuse.",
    descriere_es: "Mecanismo solar en una elegante caja de oro rosa.",
    descriere_it: "Meccanismo solare in un'elegante cassa in oro rosa.",
    pret: 740,
    pretVechi: 900,
    isSale: true,
    imagine: "ceas.jpg",
    galerie: []
  },
  {
    id: 15,
    categorie: "inele",
    nume: "Inel Persephone Rose",
    nume_en: "Persephone Rose Ring",
    nume_fr: "Bague Persephone Rose",
    nume_de: "Persephone Rose Ring",
    nume_es: "Anillo Persephone Rose",
    nume_it: "Anello Persephone Rose",
    descriere: "Aur roz cu un rubin central inspirat de grădinile Olimpului.",
    descriere_en: "Rose gold with a central ruby inspired by the gardens of Olympus.",
    descriere_fr: "Or rose avec un rubis central inspiré des jardins de l'Olympe.",
    descriere_de: "Roségold mit einem zentralen Rubin, inspiriert von den Gärten des Olymp.",
    descriere_es: "Oro rosa con un rubí central inspirado în los jardines del Olimpo.",
    descriere_it: "Oro rosa con un rubino centrale ispirato ai giardini dell'Olimpo.",
    pret: 450,
    isSale: false,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 16,
    categorie: "cercei",
    nume: "Cercei Selene Star",
    nume_en: "Selene Star Earrings",
    nume_fr: "Boucles d'oreilles Selene Star",
    nume_de: "Selene Star Ohrringe",
    nume_es: "Pendientes Selene Star",
    nume_it: "Orecchini Selene Star",
    descriere: "Stele căzătoare transpuse în diamante strălucitoare.",
    descriere_en: "Shooting stars translated into brilliant diamonds.",
    descriere_fr: "Étoiles filantes traduites en diamants brillants.",
    descriere_de: "Sternschnuppen, übersetzt in brillante Diamanten.",
    descriere_es: "Estrellas fugaces traducidas en diamantes brillantes.",
    descriere_it: "Stelle cadenti tradotte in brillanti diamanti.",
    pret: 520,
    pretVechi: 650,
    isSale: true,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 17,
    categorie: "bratari",
    nume: "Brățară Nike Victory",
    nume_en: "Nike Victory Bracelet",
    nume_fr: "Bracelet Nike Victory",
    nume_de: "Nike Victory Armband",
    nume_es: "Pulsera Nike Victory",
    nume_it: "Bracciale Nike Victory",
    descriere: "Design în formă de aripă pentru spiritele învingătoare.",
    descriere_en: "Wing-shaped design for victorious spirits.",
    descriere_fr: "Design en forme d'aile pour les esprits victorieux.",
    descriere_de: "Flügelförmiges Design für siegreiche Geister.",
    descriere_es: "Diseño en forma de ala para espíritus victoriosos.",
    descriere_it: "Design a forma di ala per spiriti vittoriosi.",
    pret: 310,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 18,
    categorie: "ceasuri",
    nume: "Ceas Ares Warrior",
    nume_en: "Ares Warrior Watch",
    nume_fr: "Montre Ares Warrior",
    nume_de: "Ares Warrior Uhr",
    nume_es: "Reloj Ares Warrior",
    nume_it: "Orologio Ares Warrior",
    descriere: "Construcție robustă din oțel carbon pentru orice provocare.",
    descriere_en: "Robust carbon steel construction for any challenge.",
    descriere_fr: "Construction robuste en acier au carbone pour tout défi.",
    descriere_de: "Robuste Carbonstahlkonstruktion für jede Herausforderung.",
    descriere_es: "Construcción robusta de acero al carbono para cualquier desafío.",
    descriere_it: "Robusta costruzione in acciaio al carbonio per ogni sfida.",
    pret: 550,
    isSale: false,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 19,
    categorie: "inele",
    nume: "Inel Gaia Earth",
    nume_en: "Gaia Earth Ring",
    nume_fr: "Bague Gaia Earth",
    nume_de: "Gaia Earth Ring",
    nume_es: "Anillo Gaia Earth",
    nume_it: "Anello Gaia Earth",
    descriere: "Un smarald vibrant montat pe o bandă cu motive florale.",
    descriere_en: "A vibrant emerald set on a band with floral motifs.",
    descriere_fr: "Une émeraude vibrante sertie sur un anneau aux motifs floraux.",
    descriere_de: "Ein lebendiger Smaragd auf einem Band mit floralen Motiven.",
    descriere_es: "Una esmeralda vibrante engastada en una banda con motivos florales.",
    descriere_it: "Un vibrante smeraldo incastonato su una fascia con motivi floreali.",
    pret: 890,
    pretVechi: 1100,
    isSale: true,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 20,
    categorie: "cercei",
    nume: "Cercei Iris Rainbow",
    nume_en: "Iris Rainbow Earrings",
    nume_fr: "Boucles d'oreilles Iris Rainbow",
    nume_de: "Iris Rainbow Ohrringe",
    nume_es: "Pendientes Iris Rainbow",
    nume_it: "Orecchini Iris Rainbow",
    descriere: "Pietre prețioase multicolore ce creează un spectru fascinant.",
    descriere_en: "Multicolor gemstones creating a fascinating spectrum.",
    descriere_fr: "Pierres multicolores créant un spectre fascinant.",
    descriere_de: "Mehrfarbige Edelsteine, die ein faszinierendes Spektrum erzeugen.",
    descriere_es: "Piedras preciosas multicolores que crean un espectro fascinante.",
    descriere_it: "Pietre preziose multicolori che creano un spettro affascinante.",
    pret: 410,
    isSale: false,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 21,
    categorie: "bratari",
    nume: "Brățară Hestia Heart",
    nume_en: "Hestia Heart Bracelet",
    nume_fr: "Bracelet Hestia Heart",
    nume_de: "Hestia Heart Armband",
    nume_es: "Pulsera Hestia Heart",
    nume_it: "Bracciale Hestia Heart",
    descriere: "Simbolul căminului, realizat din aur matificat.",
    descriere_en: "The symbol of home, crafted in matte gold.",
    descriere_fr: "Le symbole du foyer, réalisé en or mat.",
    descriere_de: "Das Symbol des Heims, gefertigt aus mattem Gold.",
    descriere_es: "El símbolo del hogar, realizado en oro mate.",
    descriere_it: "Il simbolo della casa, realizzato in oro opaco.",
    pret: 165,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 22,
    categorie: "ceasuri",
    nume: "Ceas Zephyr Wind",
    nume_en: "Zephyr Wind Watch",
    nume_fr: "Montre Zephyr Wind",
    nume_de: "Zephyr Wind Uhr",
    nume_es: "Reloj Zephyr Wind",
    nume_it: "Orologio Zephyr Wind",
    descriere: "Cel mai ușor ceas creat de noi, din aliaj de magneziu.",
    descriere_en: "Our lightest watch ever, made of magnesium alloy.",
    descriere_fr: "Notre montre la plus légère, en alliage de magnésium.",
    descriere_de: "Unsere leichteste Uhr, hergestellt aus einer Magnesiumlegierung.",
    descriere_es: "Nuestro reloj más ligero, hecho de aleación de magnesio.",
    descriere_it: "Il nostro orologio più leggero, realizzato in lega di magnesio.",
    pret: 980,
    pretVechi: 1250,
    isSale: true,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 23,
    categorie: "inele",
    nume: "Inel Pandora Secret",
    nume_en: "Pandora Secret Ring",
    nume_fr: "Bague Pandora Secret",
    nume_de: "Pandora Secret Ring",
    nume_es: "Anillo Pandora Secret",
    nume_it: "Anello Pandora Secret",
    descriere: "Un compartiment secret ascuns sub piatra de ametist.",
    descriere_en: "A secret compartment hidden under the amethyst stone.",
    descriere_fr: "Un compartiment secret caché sous la pierre d'améthyste.",
    descriere_de: "Ein geheimes Fach, versteckt unter dem Amethyststein.",
    descriere_es: "Un compartimiento secreto oculto bajo la piedra de amatista.",
    descriere_it: "Un compartimento segreto nascosto sotto la pietra di ametista.",
    pret: 240,
    isSale: false,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 24,
    categorie: "cercei",
    nume: "Cercei Medusa Coil",
    nume_en: "Medusa Coil Earrings",
    nume_fr: "Boucles d'oreilles Medusa Coil",
    nume_de: "Medusa Coil Ohrringe",
    nume_es: "Pendientes Medusa Coil",
    nume_it: "Orecchini Medusa Coil",
    descriere: "Design sub formă de șarpe din aur negru.",
    descriere_en: "Snake-shaped design in black gold.",
    descriere_fr: "Design en forme de serpent en or noir.",
    descriere_de: "Schlangenförmiges Design in Schwarzgold.",
    descriere_es: "Diseño en forma de serpiente en oro negro.",
    descriere_it: "Design a forma di serpente in oro nero.",
    pret: 370,
    isSale: false,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 25,
    categorie: "bratari",
    nume: "Brățară Clotho Thread",
    nume_en: "Clotho Thread Bracelet",
    nume_fr: "Bracelet Clotho Thread",
    nume_de: "Clotho Thread Armband",
    nume_es: "Pulsera Clotho Thread",
    nume_it: "Bracciale Clotho Thread",
    descriere: "Firul subțire al destinului înlănțuit în argint.",
    descriere_en: "The thin thread of destiny chained in silver.",
    descriere_fr: "Le fil mince du destin enchaîné en argent.",
    descriere_de: "Der dünne Faden des Schicksals, in Silber gekettet.",
    descriere_es: "El hilo delgado del destino encadenado en plata.",
    descriere_it: "Il sottile filo del destino incatenato in argento.",
    pret: 85,
    pretVechi: 120,
    isSale: true,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 26,
    categorie: "ceasuri",
    nume: "Ceas Helios Flame",
    nume_en: "Helios Flame Watch",
    nume_fr: "Montre Helios Flame",
    nume_de: "Helios Flame Uhr",
    nume_es: "Reloj Helios Flame",
    nume_it: "Orologio Helios Flame",
    descriere: "Cadran roșu ce strălucește intens sub soare.",
    descriere_en: "Red dial that shines intensely under the sun.",
    descriere_fr: "Cadran rouge qui brille intensément sous le soleil.",
    descriere_de: "Rotes Zifferblatt, das in der Sonne intensiv leuchtet.",
    descriere_es: "Esfera roja que brilla intensamente bajo el sol.",
    descriere_it: "Quadrante rosso che brilla intensamente sotto il sole.",
    pret: 620,
    isSale: false,
    imagine: "ceas.jpg",
    galerie: []
  },
  {
    id: 27,
    categorie: "inele",
    nume: "Inel Nyx Nightfall",
    nume_en: "Nyx Nightfall Ring",
    nume_fr: "Bague Nyx Nightfall",
    nume_de: "Nyx Nightfall Ring",
    nume_es: "Anillo Nyx Nightfall",
    nume_it: "Anello Nyx Nightfall",
    descriere: "O perlă neagră rară ce întruchipează misterul nopții.",
    descriere_en: "A rare black pearl embodying the mystery of the night.",
    descriere_fr: "Une perle noire rare incarnant le mystère de la nuit.",
    descriere_de: "Eine seltene schwarze Perle, die das Geheimnis der Nacht verkörpert.",
    descriere_es: "Una perla negra rara que encarna el misterio de la noche.",
    descriere_it: "Una rara perla nera che incarna il mistero della notte.",
    pret: 430,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 28,
    categorie: "cercei",
    nume: "Cercei Eos Dawn",
    nume_en: "Eos Dawn Earrings",
    nume_fr: "Boucles d'oreilles Eos Dawn",
    nume_de: "Eos Dawn Ohrringe",
    nume_es: "Pendientes Eos Dawn",
    nume_it: "Orecchini Eos Dawn",
    descriere: "Culorile răsăritului captate în opal natural.",
    descriere_en: "The colors of sunrise captured in natural opal.",
    descriere_fr: "Les couleurs du lever du soleil capturées dans l'opale.",
    descriere_de: "Die Farben des Sonnenaufgangs in natürlichem Opal festgehalten.",
    descriere_es: "Los colores del amanecer capturados en ópalo natural.",
    descriere_it: "I colori dell'alba catturati nell'opale naturale.",
    pret: 260,
    pretVechi: 350,
    isSale: true,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 29,
    categorie: "bratari",
    nume: "Brățară Tyche Fortune",
    nume_en: "Tyche Fortune Bracelet",
    nume_fr: "Bracelet Tyche Fortune",
    nume_de: "Tyche Fortune Armband",
    nume_es: "Pulsera Tyche Fortune",
    nume_it: "Bracciale Tyche Fortune",
    descriere: "Un talisman norocos cu simbolul roții destinului.",
    descriere_en: "A lucky talisman with the wheel of destiny symbol.",
    descriere_fr: "Un talisman porte-bonheur avec le symbole de la roue du destin.",
    descriere_de: "Ein Glücksbringer mit dem Symbol des Schicksalsrads.",
    descriere_es: "Un talismán de la suerte con el símbolo de la rueda del destino.",
    descriere_it: "Un talismano portafortuna con il simbolo della ruota del destino.",
    pret: 195,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 30,
    categorie: "ceasuri",
    nume: "Ceas Titan Master",
    nume_en: "Titan Master Watch",
    nume_fr: "Montre Titan Master",
    nume_de: "Titan Master Uhr",
    nume_es: "Reloj Titan Master",
    nume_it: "Orologio Titan Master",
    descriere: "Forța titanilor într-un mecanism automat robust.",
    descriere_en: "Titan strength in a robust automatic mechanism.",
    descriere_fr: "Force titanesque dans un mécanisme automatique robuste.",
    descriere_de: "Titanenkraft in einem robusten Automatikwerk.",
    descriere_es: "Fuerza titánica en un robusto mecanismo automático.",
    descriere_it: "Forza titanica in un robusto meccanismo automatico.",
    pret: 1100,
    isSale: false,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 31,
    categorie: "inele",
    nume: "Inel Electra Light",
    nume_en: "Electra Light Ring",
    nume_fr: "Bague Electra Light",
    nume_de: "Electra Light Ring",
    nume_es: "Anillo Electra Light",
    nume_it: "Anello Electra Light",
    descriere: "Topaz albastru ce scânteiază intens.",
    descriere_en: "Blue topaz that sparkles intensely.",
    descriere_fr: "Topaze bleue qui scintille intensément.",
    descriere_de: "Blautopas, der intensiv funkelt.",
    descriere_es: "Topacio azul que brilla intensamente.",
    descriere_it: "Topazio blu che scintilla intensamente.",
    pret: 340,
    pretVechi: 480,
    isSale: true,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 32,
    categorie: "cercei",
    nume: "Cercei Calliope Muse",
    nume_en: "Calliope Muse Earrings",
    nume_fr: "Boucles d'oreilles Calliope Muse",
    nume_de: "Calliope Muse Ohrringe",
    nume_es: "Pendientes Calliope Muse",
    nume_it: "Orecchini Calliope Muse",
    descriere: "Design poetic pentru cele ce inspiră arta.",
    descriere_en: "Poetic design for those who inspire art.",
    descriere_fr: "Design poétique pour celles qui inspirent l'art.",
    descriere_de: "Poetisches Design für diejenigen, die Kunst inspirieren.",
    descriere_es: "Diseño poético para quienes inspiran el arte.",
    descriere_it: "Design poetico per chi ispira l'arte.",
    pret: 215,
    isSale: false,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 33,
    categorie: "bratari",
    nume: "Brățară Hebe Youth",
    nume_en: "Hebe Youth Bracelet",
    nume_fr: "Bracelet Hebe Youth",
    nume_de: "Hebe Youth Armband",
    nume_es: "Pulsera Hebe Youth",
    nume_it: "Bracciale Hebe Youth",
    descriere: "O brățară delicată din aur roz, simbol al tinereții.",
    descriere_en: "A delicate rose gold bracelet, symbol of youth.",
    descriere_fr: "Un délicat bracelet en or rose, symbole de jeunesse.",
    descriere_de: "Ein zartes Roségold-Armband, Symbol der Jugend.",
    descriere_es: "Una delicada pulsera de oro rosa, símbolo de juventud.",
    descriere_it: "Un delicato bracciale in oro rosa, simbolo di giovinezza.",
    pret: 280,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 34,
    categorie: "ceasuri",
    nume: "Ceas Atlas Globe",
    nume_en: "Atlas Globe Watch",
    nume_fr: "Montre Atlas Globe",
    nume_de: "Atlas Globe Uhr",
    nume_es: "Reloj Atlas Globe",
    nume_it: "Orologio Atlas Globe",
    descriere: "Afișează ora pe toate meridianele lumii.",
    descriere_en: "Displays time across all world meridians.",
    descriere_fr: "Affiche l'heure sur tous les méridiens du monde.",
    descriere_de: "Zeigt die Zeit über alle Weltmeridiane an.",
    descriere_es: "Muestra la hora en todos los meridianos del mundo.",
    descriere_it: "Visualizza l'ora su tutti i meridiani del mondo.",
    pret: 820,
    pretVechi: 1050,
    isSale: true,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 35,
    categorie: "inele",
    nume: "Inel Thalia Grace",
    nume_en: "Thalia Grace Ring",
    nume_fr: "Bague Thalia Grace",
    nume_de: "Thalia Grace Ring",
    nume_es: "Anillo Thalia Grace",
    nume_it: "Anello Thalia Grace",
    descriere: "Eleganță cu pietre de peridot verde.",
    descriere_en: "Elegance with green peridot stones.",
    descriere_fr: "Élégance avec des pierres de péridot vert.",
    descriere_de: "Eleganz mit grünen Peridotsteinen.",
    descriere_es: "Elegancia con piedras de peridoto verde.",
    descriere_it: "Eleganza con pietre di peridoto verde.",
    pret: 190,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: []
  }
];
