/**
 * Baza de date oficială H-TIME - Versiune Multilingvă (6 Limbi)
 * Toate prețurile sunt exprimate în EURO (€).
 * Conversia se face automat în HTML: RO (Lei), EN ($), FR/DE/ES/IT (€).
 */

const produse = [
  {
    id: 1,
    categorie: "ceasuri",
    nume: "Ceas Rolex Oyster Luxury",
    nume_en: "Rolex Oyster Luxury Watch",
    nume_fr: "Montre Rolex Oyster de Luxe",
    nume_de: "Rolex Oyster Luxusuhr",
    nume_es: "Reloj Rolex Oyster Luxury",
    nume_it: "Orologio Rolex Oyster Luxury",
    descriere: "O piesă atemporală ce îmbină precizia elvețiană cu eleganța aurului de 18k. Un simbol al succesului și al rafinamentului absolut.",
    descriere_en: "A timeless piece combining Swiss precision with 18k gold elegance. A symbol of success and absolute refinement.",
    pret: 950,
    pretVechi: 1200,
    isSale: true,
    imagine: "ceas1.jpg",
    galerie: ["ceas2.jpg", "ceas.jpg"]
  },
  {
    id: 2,
    categorie: "inele",
    nume: "Inel Aur Hera",
    nume_en: "Hera Gold Ring",
    nume_fr: "Bague en Or Hera",
    nume_de: "Hera Goldring",
    nume_es: "Anillo de Oro Hera",
    nume_it: "Anello in Oro Hera",
    descriere: "Inspirat de zeița Hera, acest inel din aur masiv simbolizează devotamentul și puterea feminină. Ideal pentru ocazii memorabile.",
    descriere_en: "Inspired by the goddess Hera, this solid gold ring symbolizes devotion and feminine power. Ideal for memorable occasions.",
    pret: 150,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: ["inel2.jpg", "ring.jpg"]
  },
  {
    id: 3,
    categorie: "cercei",
    nume: "Cercei Diamond Drop",
    nume_en: "Diamond Drop Earrings",
    nume_fr: "Boucles d'oreilles Diamond Drop",
    nume_de: "Diamond Drop Ohrringe",
    nume_es: "Pendientes Diamond Drop",
    nume_it: "Orecchini Diamond Drop",
    descriere: "Cercei eleganți cu diamante atent selecționate, creați pentru a capta lumina la fiecare mișcare. Rafinament pur pentru o prezență divină.",
    descriere_en: "Elegant earrings with carefully selected diamonds, designed to catch the light with every move. Pure refinement for a divine presence.",
    pret: 320,
    pretVechi: 450,
    isSale: true,
    imagine: "cercel1.jpg",
    galerie: ["earring.jpg"]
  },
  {
    id: 4,
    categorie: "ceasuri",
    nume: "Ceas Chronos Silver",
    nume_en: "Chronos Silver Watch",
    nume_fr: "Montre Chronos Silver",
    nume_de: "Chronos Silver Uhr",
    nume_es: "Reloj Chronos Silver",
    nume_it: "Orologio Chronos Silver",
    descriere: "Un design minimalist din oțel inoxidabil de cea mai înaltă calitate. Chronos Silver este partenerul perfect pentru stilul business modern.",
    descriere_en: "A minimalist design made of high-quality stainless steel. Chronos Silver is the perfect partner for modern business style.",
    pret: 420,
    isSale: false,
    imagine: "ceas2.jpg",
    galerie: ["ceas.jpg"]
  },
  {
    id: 5,
    categorie: "inele",
    nume: "Inel Safir Royal",
    nume_en: "Royal Sapphire Ring",
    nume_fr: "Bague Saphir Royal",
    nume_de: "Königlicher Saphirring",
    nume_es: "Anillo de Zafiro Real",
    nume_it: "Anello Zaffiro Reale",
    descriere: "Un safir profund înconjurat de diamante mici, montat pe o bandă delicată de aur alb. O bijuterie demnă de o regină.",
    descriere_en: "A deep sapphire surrounded by small diamonds, set on a delicate white gold band. A piece of jewelry fit for a queen.",
    pret: 580,
    pretVechi: 720,
    isSale: true,
    imagine: "inel2.jpg",
    galerie: ["ring.jpg", "inel1.jpg"]
  },
  {
    id: 6,
    categorie: "bratari",
    nume: "Brățară Gold Link",
    nume_en: "Gold Link Bracelet",
    nume_fr: "Bracelet Gold Link",
    nume_de: "Gold Link Armband",
    nume_es: "Pulsera Gold Link",
    nume_it: "Bracciale Gold Link",
    descriere: "Zale lucrate manual ce reflectă măiestria bijutierilor H-TIME. Această brățară adaugă un accent de lux oricărei ținute.",
    descriere_en: "Handcrafted links reflecting the craftsmanship of H-TIME jewelers. This bracelet adds a luxury accent to any outfit.",
    pret: 210,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 7,
    categorie: "cercei",
    nume: "Cercei Perla Afroditei",
    nume_en: "Aphrodite's Pearl Earrings",
    nume_fr: "Boucles d'oreilles Perle d'Aphrodite",
    nume_de: "Perlenohrringe der Aphrodite",
    nume_es: "Pendientes Perla de Afrodita",
    nume_it: "Orecchini Perla di Afrodite",
    descriere: "Perle naturale de apă sărată cu o strălucire sidefată unică, inspirate de frumusețea zeiței iubirii.",
    descriere_en: "Natural saltwater pearls with a unique pearlescent glow, inspired by the beauty of the goddess of love.",
    pret: 180,
    isSale: false,
    imagine: "earring.jpg",
    galerie: ["cercel1.jpg"]
  },
  {
    id: 8,
    categorie: "ceasuri",
    nume: "Ceas Onyx Night",
    nume_en: "Onyx Night Watch",
    nume_fr: "Montre Onyx Night",
    nume_de: "Onyx Night Uhr",
    nume_es: "Reloj Onyx Night",
    nume_it: "Orologio Onyx Night",
    descriere: "Eleganță în negru absolut. Un ceas rar cu cadran din onix și curea din piele de crocodil, creat pentru momente exclusiviste.",
    descriere_en: "Elegance in absolute black. A rare watch with an onyx dial and crocodile leather strap, created for exclusive moments.",
    pret: 850,
    pretVechi: 1100,
    isSale: true,
    imagine: "ceas.jpg",
    galerie: ["ceas1.jpg", "ceas2.jpg"]
  },
  {
    id: 9,
    categorie: "ceasuri",
    nume: "Ceas Olympus Gold",
    nume_en: "Olympus Gold Watch",
    nume_fr: "Montre Olympus Gold",
    nume_de: "Olympus Gold Uhr",
    nume_es: "Reloj Olympus Gold",
    nume_it: "Orologio Olympus Gold",
    descriere: "Puterea zeilor la încheietura mâinii tale. Placat cu aur de 24k.",
    pret: 1250,
    pretVechi: 1500,
    isSale: true,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 10,
    categorie: "ceasuri",
    nume: "Ceas Poseidon Deep Blue",
    nume_en: "Poseidon Deep Blue Watch",
    nume_fr: "Montre Poseidon Deep Blue",
    nume_de: "Poseidon Deep Blue Uhr",
    nume_es: "Reloj Poseidon Deep Blue",
    nume_it: "Orologio Poseidon Deep Blue",
    descriere: "Rezistență extremă la apă și un cadran de un albastru oceanic hipnotizant.",
    pret: 680,
    isSale: false,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 11,
    categorie: "inele",
    nume: "Inel Artemis Moon",
    nume_en: "Artemis Moon Ring",
    nume_fr: "Bague Artemis Moon",
    nume_de: "Artemis Moon Ring",
    nume_es: "Anillo Artemis Moon",
    nume_it: "Anello Artemis Moon",
    descriere: "Argint pur cu o piatră a lunii ce reflectă lumina nocturnă.",
    pret: 120,
    pretVechi: 180,
    isSale: true,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 12,
    categorie: "cercei",
    nume: "Cercei Athena Wisdom",
    nume_en: "Athena Wisdom Earrings",
    nume_fr: "Boucles d'oreilles Athena Wisdom",
    nume_de: "Athena Wisdom Ohrringe",
    nume_es: "Pendientes Athena Wisdom",
    nume_it: "Orecchini Athena Wisdom",
    descriere: "Simbolul bufniței sculptat în aur alb, decorat cu safire mici.",
    pret: 290,
    isSale: false,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 13,
    categorie: "bratari",
    nume: "Brățară Hermes Speed",
    nume_en: "Hermes Speed Bracelet",
    nume_fr: "Bracelet Hermes Speed",
    nume_de: "Hermes Speed Armband",
    nume_es: "Pulsera Hermes Speed",
    nume_it: "Bracciale Hermes Speed",
    descriere: "O brățară din piele fină cu accente din titan argintiu.",
    pret: 95,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 14,
    categorie: "ceasuri",
    nume: "Ceas Apollo Sun",
    nume_en: "Apollo Sun Watch",
    nume_fr: "Montre Apollo Sun",
    nume_de: "Apollo Sun Uhr",
    nume_es: "Reloj Apollo Sun",
    nume_it: "Orologio Apollo Sun",
    descriere: "Mecanism solar de ultimă generație într-o carcasă de aur roz.",
    pret: 740,
    pretVechi: 900,
    isSale: true,
    imagine: "ceas.jpg",
    galerie: []
  },
  {
    id: 15,
    categorie: "inele",
    nume: "Inel Persephone Rose",
    nume_en: "Persephone Rose Ring",
    nume_fr: "Bague Persephone Rose",
    nume_de: "Persephone Rose Ring",
    nume_es: "Anillo Persephone Rose",
    nume_it: "Anello Persephone Rose",
    descriere: "Aur roz cu un rubin central ce amintește de grădinile Olimpului.",
    pret: 450,
    isSale: false,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 16,
    categorie: "cercei",
    nume: "Cercei Selene Star",
    nume_en: "Selene Star Earrings",
    nume_fr: "Boucles d'oreilles Selene Star",
    nume_de: "Selene Star Ohrringe",
    nume_es: "Pendientes Selene Star",
    nume_it: "Orecchini Selene Star",
    descriere: "Stele căzătoare transpuse în diamante strălucitoare.",
    pret: 520,
    pretVechi: 650,
    isSale: true,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 17,
    categorie: "bratari",
    nume: "Brățară Nike Victory",
    nume_en: "Nike Victory Bracelet",
    nume_fr: "Bracelet Nike Victory",
    nume_de: "Nike Victory Armband",
    nume_es: "Pulsera Nike Victory",
    nume_it: "Bracciale Nike Victory",
    descriere: "Pentru spiritele învingătoare. Design în formă de aripă de înger.",
    pret: 310,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 18,
    categorie: "ceasuri",
    nume: "Ceas Ares Warrior",
    nume_en: "Ares Warrior Watch",
    nume_fr: "Montre Ares Warrior",
    nume_de: "Ares Warrior Uhr",
    nume_es: "Reloj Ares Warrior",
    nume_it: "Orologio Ares Warrior",
    descriere: "Construcție robustă din oțel carbon, rezistent la orice provocare.",
    pret: 550,
    isSale: false,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 19,
    categorie: "inele",
    nume: "Inel Gaia Earth",
    nume_en: "Gaia Earth Ring",
    nume_fr: "Bague Gaia Earth",
    nume_de: "Gaia Earth Ring",
    nume_es: "Anillo Gaia Earth",
    nume_it: "Anello Gaia Earth",
    descriere: "Un smarald vibrant montat pe o bandă cu motive florale.",
    pret: 890,
    pretVechi: 1100,
    isSale: true,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 20,
    categorie: "cercei",
    nume: "Cercei Iris Rainbow",
    nume_en: "Iris Rainbow Earrings",
    nume_fr: "Boucles d'oreilles Iris Rainbow",
    nume_de: "Iris Rainbow Ohrringe",
    nume_es: "Pendientes Iris Rainbow",
    nume_it: "Orecchini Iris Rainbow",
    descriere: "Pietre prețioase multicolore ce creează un spectru fascinant.",
    pret: 410,
    isSale: false,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 21,
    categorie: "bratari",
    nume: "Brățară Hestia Heart",
    nume_en: "Hestia Heart Bracelet",
    nume_fr: "Bracelet Hestia Heart",
    nume_de: "Hestia Heart Armband",
    nume_es: "Pulsera Hestia Heart",
    nume_it: "Bracciale Hestia Heart",
    descriere: "Simbolul căminului cald, realizat din aur matificat.",
    pret: 165,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 22,
    categorie: "ceasuri",
    nume: "Ceas Zephyr Wind",
    nume_en: "Zephyr Wind Watch",
    nume_fr: "Montre Zephyr Wind",
    nume_de: "Zephyr Wind Uhr",
    nume_es: "Reloj Zephyr Wind",
    nume_it: "Orologio Zephyr Wind",
    descriere: "Cel mai ușor ceas creat vreodată, din aliaj de magneziu.",
    pret: 980,
    pretVechi: 1250,
    isSale: true,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 23,
    categorie: "inele",
    nume: "Inel Pandora Secret",
    nume_en: "Pandora Secret Ring",
    nume_fr: "Bague Pandora Secret",
    nume_de: "Pandora Secret Ring",
    nume_es: "Anillo Pandora Secret",
    nume_it: "Anello Pandora Secret",
    descriere: "Un compartiment secret ascuns sub piatra de ametist.",
    pret: 240,
    isSale: false,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 24,
    categorie: "cercei",
    nume: "Cercei Medusa Coil",
    nume_en: "Medusa Coil Earrings",
    nume_fr: "Boucles d'oreilles Medusa Coil",
    nume_de: "Medusa Coil Ohrringe",
    nume_es: "Pendientes Medusa Coil",
    nume_it: "Orecchini Medusa Coil",
    descriere: "Design avangardist sub formă de șarpe, din aur negru.",
    pret: 370,
    isSale: false,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 25,
    categorie: "bratari",
    nume: "Brățară Clotho Thread",
    nume_en: "Clotho Thread Bracelet",
    nume_fr: "Bracelet Clotho Thread",
    nume_de: "Clotho Thread Armband",
    nume_es: "Pulsera Clotho Thread",
    nume_it: "Bracciale Clotho Thread",
    descriere: "Firul subțire al destinului înlănțuit în argint fin.",
    pret: 85,
    pretVechi: 120,
    isSale: true,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 26,
    categorie: "ceasuri",
    nume: "Ceas Helios Flame",
    nume_en: "Helios Flame Watch",
    nume_fr: "Montre Helios Flame",
    nume_de: "Helios Flame Uhr",
    nume_es: "Reloj Helios Flame",
    nume_it: "Orologio Helios Flame",
    descriere: "Cadran roșu aprins ce strălucește sub razele soarelui.",
    pret: 620,
    isSale: false,
    imagine: "ceas.jpg",
    galerie: []
  },
  {
    id: 27,
    categorie: "inele",
    nume: "Inel Nyx Nightfall",
    nume_en: "Nyx Nightfall Ring",
    nume_fr: "Bague Nyx Nightfall",
    nume_de: "Nyx Nightfall Ring",
    nume_es: "Anillo Nyx Nightfall",
    nume_it: "Anello Nyx Nightfall",
    descriere: "O perlă neagră rară ce întruchipează misterul nopții.",
    pret: 430,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: []
  },
  {
    id: 28,
    categorie: "cercei",
    nume: "Cercei Eos Dawn",
    nume_en: "Eos Dawn Earrings",
    nume_fr: "Boucles d'oreilles Eos Dawn",
    nume_de: "Eos Dawn Ohrringe",
    nume_es: "Pendientes Eos Dawn",
    nume_it: "Orecchini Eos Dawn",
    descriere: "Culorile răsăritului captate în opal natural.",
    pret: 260,
    pretVechi: 350,
    isSale: true,
    imagine: "cercel1.jpg",
    galerie: []
  },
  {
    id: 29,
    categorie: "bratari",
    nume: "Brățară Tyche Fortune",
    nume_en: "Tyche Fortune Bracelet",
    nume_fr: "Bracelet Tyche Fortune",
    nume_de: "Tyche Fortune Armband",
    nume_es: "Pulsera Tyche Fortune",
    nume_it: "Bracciale Tyche Fortune",
    descriere: "Un talisman norocos cu simbolul roții norocului.",
    pret: 195,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 30,
    categorie: "ceasuri",
    nume: "Ceas Titan Master",
    nume_en: "Titan Master Watch",
    nume_fr: "Montre Titan Master",
    nume_de: "Titan Master Uhr",
    nume_es: "Reloj Titan Master",
    nume_it: "Orologio Titan Master",
    descriere: "Forța titanilor într-un mecanism automat indestructibil.",
    pret: 1100,
    isSale: false,
    imagine: "ceas1.jpg",
    galerie: []
  },
  {
    id: 31,
    categorie: "inele",
    nume: "Inel Electra Light",
    nume_en: "Electra Light Ring",
    nume_fr: "Bague Electra Light",
    nume_de: "Electra Light Ring",
    nume_es: "Anillo Electra Light",
    nume_it: "Anello Electra Light",
    descriere: "Piatră de topaz albastru ce scânteiază ca un fulger.",
    pret: 340,
    pretVechi: 480,
    isSale: true,
    imagine: "inel2.jpg",
    galerie: []
  },
  {
    id: 32,
    categorie: "cercei",
    nume: "Cercei Calliope Muse",
    nume_en: "Calliope Muse Earrings",
    nume_fr: "Boucles d'oreilles Calliope Muse",
    nume_de: "Calliope Muse Ohrringe",
    nume_es: "Pendientes Calliope Muse",
    nume_it: "Orecchini Calliope Muse",
    descriere: "Design poetic pentru cele care inspiră arta în ceilalți.",
    pret: 215,
    isSale: false,
    imagine: "earring.jpg",
    galerie: []
  },
  {
    id: 33,
    categorie: "bratari",
    nume: "Brățară Hebe Youth",
    nume_en: "Hebe Youth Bracelet",
    nume_fr: "Bracelet Hebe Youth",
    nume_de: "Hebe Youth Armband",
    nume_es: "Pulsera Hebe Youth",
    nume_it: "Bracciale Hebe Youth",
    descriere: "O brățară delicată din aur roz, simbol al tinereții veșnice.",
    pret: 280,
    isSale: false,
    imagine: "ring.jpg",
    galerie: []
  },
  {
    id: 34,
    categorie: "ceasuri",
    nume: "Ceas Atlas Globe",
    nume_en: "Atlas Globe Watch",
    nume_fr: "Montre Atlas Globe",
    nume_de: "Atlas Globe Uhr",
    nume_es: "Reloj Atlas Globe",
    nume_it: "Orologio Atlas Globe",
    descriere: "Afișează ora pe toate meridianele lumii.",
    pret: 820,
    pretVechi: 1050,
    isSale: true,
    imagine: "ceas2.jpg",
    galerie: []
  },
  {
    id: 35,
    categorie: "inele",
    nume: "Inel Thalia Grace",
    nume_en: "Thalia Grace Ring",
    nume_fr: "Bague Thalia Grace",
    nume_de: "Thalia Grace Ring",
    nume_es: "Anillo Thalia Grace",
    nume_it: "Anello Thalia Grace",
    descriere: "Eleganță veselă cu pietre de peridot verde crud.",
    pret: 190,
    isSale: false,
    imagine: "inel1.jpg",
    galerie: []
  }
];
